import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "./Header";
import Sidebar from "./Sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`} style={{ backgroundColor: '#ffffff' }}>
        
        {/* Global Fixed Header */}
        <Header />

        {/* Global Layout Container (Pushed below header) */}
        <div className="flex max-w-7xl mx-auto w-full px-8 pt-32 pb-20">
          
          {/* Static Sidebar on Left */}
          <aside className="hidden md:block w-[280px] fixed h-[calc(100vh-8rem)] overflow-y-auto">
             <Sidebar />
          </aside>
          
          {/* Scrollable Main Content on Right */}
          <main className="flex-1 md:ml-[300px] min-h-[50vh]">
            {children}
          </main>
          
        </div>
        
      </body>
    </html>
  );
}
